export const applyAnimationScaleUpTr = () => `
/* ----------------------------------------------
* Generated by Animista on 2023-10-24 20:58:32
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation scale-up-tr
* ----------------------------------------
*/
@-webkit-keyframes scale-up-tr {
 0% {
   -webkit-transform: scale(0);
           transform: scale(0);
   -webkit-transform-origin: 100% 0%;
           transform-origin: 100% 0%;
 }
 100% {
   -webkit-transform: scale(1);
           transform: scale(1);
   -webkit-transform-origin: 100% 0%;
           transform-origin: 100% 0%;
 }
}
@keyframes scale-up-tr {
 0% {
   -webkit-transform: scale(0);
           transform: scale(0);
   -webkit-transform-origin: 100% 0%;
           transform-origin: 100% 0%;
 }
 100% {
   -webkit-transform: scale(1);
           transform: scale(1);
   -webkit-transform-origin: 100% 0%;
           transform-origin: 100% 0%;
 }
}
-webkit-animation: scale-up-tr 0.3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
	        animation: scale-up-tr 0.3s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;

`;

export const applyAnimationSlideBottom = () => `
/* ----------------------------------------------
        * Generated by Animista on 2023-10-24 21:2:42
        * Licensed under FreeBSD License.
        * See http://animista.net/license for more info. 
        * w: http://animista.net, t: @cssanimista
        * ---------------------------------------------- */
       
       /**
        * ----------------------------------------
        * animation slide-bottom
        * ----------------------------------------
        */
       @-webkit-keyframes slide-bottom {
         0% {
           -webkit-transform: translateY(0);
                   transform: translateY(0);
         }
         100% {
           -webkit-transform: translateY(100px);
                   transform: translateY(100px);
         }
       }
       @keyframes slide-bottom {
         0% {
           -webkit-transform: translateY(-20px);
                   transform: translateY(-20px);
         }
         100% {
           -webkit-transform: translateY(0px);
                   transform: translateY(0px);
         }
       }
        -webkit-animation: slide-bottom 0.2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	animation: slide-bottom 0.2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;

`;
